services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: appIncendios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d appIncendios"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

    #Enviroment para correrlo en local
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: appIncendios
      REDIS_URL: redis://redis:6379
      DB_SSL: "false"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    command: ["node","dist/server.js"]

volumes:
  db_data:
