version: "3.9"

name: app-incendios

services:
  pg:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ:-America/Guatemala}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-net

  pg-backup:
    image: prodrigestivill/postgres-backup-local:16
    container_name: pg-backup
    depends_on:
      pg:
        condition: service_healthy
    environment:
      POSTGRES_HOST: pg
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "30 2 * * *"       # diario a las 2:30 AM
      BACKUP_KEEP_DAYS: 7
      BACKUP_COMPRESSION: "gzip"
      BACKUP_DIR: /backups
      TZ: ${TZ:-America/Guatemala}
    volumes:
      - pg-backups:/backups
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: app-incendios:latest
    container_name: api
    env_file:
      - .env
    environment:
      NODE_ENV: production
      TZ: ${TZ:-America/Guatemala}
      LOG_LEVEL: ${LOG_LEVEL:-info}

      # Base de datos interna
      DB_HOST: pg
      DB_PORT: 5432
      DB_SSL: "false"

      # Redis interno
      REDIS_URL: redis://redis:6379

      # Secretos heredados del .env
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "4000:4000"
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/health/liveness || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-net

volumes:
  pg-data:
  pg-backups:

networks:
  app-net:
    driver: bridge
