services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production   # <- omite devDeps en deps/prune
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      TZ: America/Guatemala
      LOG_LEVEL: info
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: "true"
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
