import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1759626803525 implements MigrationInterface {
    name = 'Baseline1759626803525'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("rol_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "descripcion" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre"), CONSTRAINT "PK_24cab7a48925a16ac7f4aee590c" PRIMARY KEY ("rol_uuid"))`);
        await queryRunner.query(`CREATE TABLE "instituciones" ("institucion_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_f54d2a3573c21c9effef8ae5712" UNIQUE ("nombre"), CONSTRAINT "PK_1f4740061443ac9950878ec985c" PRIMARY KEY ("institucion_uuid"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("usuario_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text, "apellido" text, "telefono" text, "email" text, "password_hash" text NOT NULL, "is_admin" boolean NOT NULL DEFAULT false, "ultimo_login" TIMESTAMP WITH TIME ZONE, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "rol_uuid" uuid NOT NULL, "institucion_uuid" uuid, CONSTRAINT "PK_d5ba74a5cfa5fdc7233ba2e632a" PRIMARY KEY ("usuario_uuid"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_usuarios_email_notnull" ON "usuarios" ("email") WHERE "email" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "estado_incendio" ("estado_incendio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "orden" integer NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b2656deef89f9ea62cce63e99ec" UNIQUE ("codigo"), CONSTRAINT "PK_b6aabb66588f03a19763ed0f170" PRIMARY KEY ("estado_incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "incendios" ("incendio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "requiere_aprobacion" boolean NOT NULL DEFAULT true, "aprobado" boolean NOT NULL DEFAULT false, "aprobado_en" TIMESTAMP WITH TIME ZONE, "rechazado_en" TIMESTAMP WITH TIME ZONE, "motivo_rechazo" text, "titulo" text, "descripcion" text, "centroide" geometry(Point,4326), "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "creado_por_uuid" uuid NOT NULL, "aprobado_por" uuid, "rechazado_por" uuid, "estado_incendio_uuid" uuid NOT NULL, CONSTRAINT "PK_6c7b9e2d55a7b6ae15449667281" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_incendios_estado_aprobado" ON "incendios" ("estado_incendio_uuid", "aprobado") `);
        await queryRunner.query(`CREATE TABLE "incendio_registro_responsable" ("incendio_uuid" uuid NOT NULL, "nombre" text NOT NULL, "cargo" text, "telefono" text, "correo" text, "observaciones" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "institucion_uuid" uuid, CONSTRAINT "PK_dcc100713eeb9bd4c5e7b181695" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "medios" ("medio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_cdf1be33891d0fdef9990ff7649" UNIQUE ("nombre"), CONSTRAINT "PK_d95c98c8cfe783f2852f33d055a" PRIMARY KEY ("medio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "departamentos" ("departamento_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_324052d75576efdbc10ba3e8997" UNIQUE ("nombre"), CONSTRAINT "PK_73b30694d3e85fecea350dc8c95" PRIMARY KEY ("departamento_uuid"))`);
        await queryRunner.query(`CREATE TABLE "municipios" ("municipio_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "departamento_uuid" uuid NOT NULL, CONSTRAINT "PK_c48a5aceeed09300c9e7a690340" PRIMARY KEY ("municipio_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_municipios_depto_nombre" ON "municipios" ("departamento_uuid", "nombre") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_municipios_depto_nombre" ON "municipios" ("departamento_uuid", "nombre") `);
        await queryRunner.query(`CREATE TABLE "reportes" ("reporte_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "reportado_por_nombre" text NOT NULL, "telefono" text, "reportado_en" TIMESTAMP WITH TIME ZONE NOT NULL, "ubicacion" geometry(Point,4326) NOT NULL, "lugar_poblado" text, "finca" text, "observaciones" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid, "reportado_por_uuid" uuid NOT NULL, "institucion_uuid" uuid, "medio_uuid" uuid NOT NULL, "departamento_uuid" uuid, "municipio_uuid" uuid, CONSTRAINT "PK_a3d6529b5aef90a1fea9cdb7940" PRIMARY KEY ("reporte_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_reportes_reportado_en" ON "reportes" ("reportado_en") `);
        await queryRunner.query(`CREATE INDEX "idx_reportes_incendio" ON "reportes" ("incendio_uuid") `);
        await queryRunner.query(`CREATE TABLE "incendio_estado_historial" ("historial_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "observacion" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, "estado_incendio_uuid" uuid NOT NULL, "cambiado_por" uuid, CONSTRAINT "PK_883562229677f4e9c4c96cf1376" PRIMARY KEY ("historial_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_historial_incendio_fecha" ON "incendio_estado_historial" ("incendio_uuid", "creado_en") `);
        await queryRunner.query(`CREATE TABLE "fotos_reporte" ("foto_reporte_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" text NOT NULL, "credito" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "reporte_uuid" uuid NOT NULL, CONSTRAINT "PK_288577555e842613a2f8831bd06" PRIMARY KEY ("foto_reporte_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_fotos_reporte_reporte" ON "fotos_reporte" ("reporte_uuid") `);
        await queryRunner.query(`CREATE TABLE "zonas_afectadas" ("zona_afectada_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "geom" geometry(MultiPolygon,4326) NOT NULL, "fecha" date NOT NULL, "fuente" text, "metodo" text, "area_ha" numeric, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, CONSTRAINT "PK_b34401004baad53d3a6c32e33f8" PRIMARY KEY ("zona_afectada_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_zonas_afectadas_incendio_fecha" ON "zonas_afectadas" ("incendio_uuid", "fecha") `);
        await queryRunner.query(`CREATE TABLE "tipos_incendio" ("tipo_incendio_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_73b407a180bef892cd3703ec3bc" PRIMARY KEY ("tipo_incendio_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_operaciones" ("incendio_uuid" uuid NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "tipo_incendio_principal_id" text, CONSTRAINT "PK_9c7a2d475639f54d65d4d6202ef" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "puntos_calor" ("punto_calor_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "fuente" text NOT NULL, "instrument" text NOT NULL, "satellite" text NOT NULL, "version" text, "acq_date" date NOT NULL, "acq_time" integer NOT NULL, "daynight" text, "confidence" numeric, "frp" numeric, "brightness" numeric, "bright_ti4" numeric, "bright_ti5" numeric, "scan" numeric, "track" numeric, "geom" geometry(Point,4326) NOT NULL, "region" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid, CONSTRAINT "PK_e138bd05e2ad8cf6dcc5ce14b1f" PRIMARY KEY ("punto_calor_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_puntos_calor_fecha" ON "puntos_calor" ("acq_date") `);
        await queryRunner.query(`CREATE TABLE "cierre_eventos_operativos" ("evento_operativo_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_evento" text NOT NULL, "categoria" text NOT NULL, "recurso_id" text, "ocurrio_en" TIMESTAMP WITH TIME ZONE NOT NULL, "nota" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, "creado_por" uuid, CONSTRAINT "PK_a90621ae0868b96e5af4cb85997" PRIMARY KEY ("evento_operativo_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_eventos_operativos_incendio_fecha" ON "cierre_eventos_operativos" ("incendio_uuid", "ocurrio_en") `);
        await queryRunner.query(`CREATE TABLE "actualizaciones" ("actualizacion_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" text NOT NULL, "descripcion_corta" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, "creado_por" uuid, "historial_uuid" uuid, "reporte_uuid" uuid, "foto_reporte_uuid" uuid, "responsable_incendio_uuid" uuid, "cierre_incendio_uuid" uuid, "zona_afectada_uuid" uuid, "punto_calor_uuid" uuid, "evento_operativo_uuid" uuid, CONSTRAINT "PK_4cae633538702069815393c0816" PRIMARY KEY ("actualizacion_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_actualizaciones_creado_en" ON "actualizaciones" ("creado_en") `);
        await queryRunner.query(`CREATE INDEX "idx_actualizaciones_incendio_fecha" ON "actualizaciones" ("incendio_uuid", "creado_en") `);
        await queryRunner.query(`CREATE TABLE "cierre_topografia" ("incendio_uuid" uuid NOT NULL, "plano_pct" numeric NOT NULL DEFAULT '0', "ondulado_pct" numeric NOT NULL DEFAULT '0', "quebrado_pct" numeric NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_52225407ca726d1865e5b058405" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "cierre_tecnicas_extincion" ("incendio_uuid" uuid NOT NULL, "tecnica" text NOT NULL, "pct" numeric NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d53d588fa255007163fabb02474" PRIMARY KEY ("incendio_uuid", "tecnica"))`);
        await queryRunner.query(`CREATE TABLE "cierre_superficie" ("incendio_uuid" uuid NOT NULL, "area_total_ha" numeric NOT NULL DEFAULT '0', "dentro_ap_ha" numeric NOT NULL DEFAULT '0', "fuera_ap_ha" numeric NOT NULL DEFAULT '0', "nombre_ap" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_53946f9c9e3dfd1ec455bab8c73" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "cierre_superficie_vegetacion" ("superficie_vegetacion_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "ubicacion" text NOT NULL, "categoria" text NOT NULL, "subtipo" text, "area_ha" numeric NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "incendio_uuid" uuid NOT NULL, CONSTRAINT "PK_f392518e9b6f55dcbb8738de928" PRIMARY KEY ("superficie_vegetacion_uuid"))`);
        await queryRunner.query(`CREATE INDEX "idx_superficie_veg_incendio_categoria" ON "cierre_superficie_vegetacion" ("incendio_uuid", "categoria") `);
        await queryRunner.query(`CREATE TABLE "cierre_secuencia_control" ("incendio_uuid" uuid NOT NULL, "llegada_medios_terrestres_at" TIMESTAMP WITH TIME ZONE, "llegada_medios_aereos_at" TIMESTAMP WITH TIME ZONE, "controlado_at" TIMESTAMP WITH TIME ZONE, "extinguido_at" TIMESTAMP WITH TIME ZONE, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_92db310748a2f72967fdd5aa7c5" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "tipo_propiedad" ("tipo_propiedad_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_273e77c7435341872e0b3fc9e31" PRIMARY KEY ("tipo_propiedad_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_propiedad" ("incendio_uuid" uuid NOT NULL, "tipo_propiedad_id" text NOT NULL, "usado" boolean NOT NULL DEFAULT false, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0efcd0e8c2281b0b5fbf566e283" PRIMARY KEY ("incendio_uuid", "tipo_propiedad_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_meteorologia" ("incendio_uuid" uuid NOT NULL, "temp_c" numeric, "hr_pct" numeric, "viento_vel" numeric, "viento_dir" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_257a2b8a6662c067b1e072c68a0" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "medios_terrestres_catalogo" ("medio_terrestre_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6417f53fdb74d3a3ebf9af40f8c" PRIMARY KEY ("medio_terrestre_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_medios_terrestres" ("incendio_uuid" uuid NOT NULL, "medio_terrestre_id" text NOT NULL, "cantidad" integer NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e319aebc011c8f1aaf64b10b5d8" PRIMARY KEY ("incendio_uuid", "medio_terrestre_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_medios_instituciones" ("incendio_uuid" uuid NOT NULL, "institucion_uuid" uuid NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1c807ce517e56df3c98ef8b0ec4" PRIMARY KEY ("incendio_uuid", "institucion_uuid"))`);
        await queryRunner.query(`CREATE TABLE "medios_acuaticos_catalogo" ("medio_acuatico_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ff888581cd1bbd5c2016e64ea40" PRIMARY KEY ("medio_acuatico_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_medios_acuaticos" ("incendio_uuid" uuid NOT NULL, "medio_acuatico_id" text NOT NULL, "cantidad" integer NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_5303da7a06afdeab4961f053c9e" PRIMARY KEY ("incendio_uuid", "medio_acuatico_id"))`);
        await queryRunner.query(`CREATE TABLE "medios_aereos_catalogo" ("medio_aereo_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d59ae0c9d7cb54691778bfd3b9c" PRIMARY KEY ("medio_aereo_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_medios_aereos" ("incendio_uuid" uuid NOT NULL, "medio_aereo_id" text NOT NULL, "pct" numeric NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c1df54b2d44821b23be1f6eaea2" PRIMARY KEY ("incendio_uuid", "medio_aereo_id"))`);
        await queryRunner.query(`CREATE TABLE "iniciado_junto_a_catalogo" ("iniciado_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_08e2a3acbfe9d0ab3fcf7728740" PRIMARY KEY ("iniciado_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_iniciado_junto_a" ("incendio_uuid" uuid NOT NULL, "otro_texto" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "iniciado_id" text NOT NULL, CONSTRAINT "PK_572915a590279d25d1aefda0134" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "cierre_composicion_tipo" ("incendio_uuid" uuid NOT NULL, "tipo_incendio_id" text NOT NULL, "pct" numeric NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e9d4b12adb8872c39753949715d" PRIMARY KEY ("incendio_uuid", "tipo_incendio_id"))`);
        await queryRunner.query(`CREATE TABLE "causas_catalogo" ("causa_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ff90796bd4161834658b65ba7e9" PRIMARY KEY ("causa_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_causa" ("incendio_uuid" uuid NOT NULL, "otro_texto" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, "causa_id" text NOT NULL, CONSTRAINT "PK_ad974789d5c277b5afe892defac" PRIMARY KEY ("incendio_uuid"))`);
        await queryRunner.query(`CREATE TABLE "abastos_catalogo" ("abasto_id" text NOT NULL, "nombre" text NOT NULL, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2690fa67cdf01ee676fe4a738de" PRIMARY KEY ("abasto_id"))`);
        await queryRunner.query(`CREATE TABLE "cierre_abastos" ("incendio_uuid" uuid NOT NULL, "abasto_id" text NOT NULL, "cantidad" integer NOT NULL DEFAULT '0', "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "eliminado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_75e27d8aa42fafab017538b57f0" PRIMARY KEY ("incendio_uuid", "abasto_id"))`);
        await queryRunner.query(`CREATE TABLE "auditoria_eventos" ("auditoria_uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "tabla" text NOT NULL, "registro_id" text NOT NULL, "accion" text NOT NULL, "antes" jsonb, "despues" jsonb, "usuario_uuid" uuid, "ip" text, "user_agent" text, "creado_en" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_597e337f6469aeadbd65c347977" PRIMARY KEY ("auditoria_uuid"))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_rol_uuid" FOREIGN KEY ("rol_uuid") REFERENCES "roles"("rol_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_institucion_uuid" FOREIGN KEY ("institucion_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_creado_por_uuid" FOREIGN KEY ("creado_por_uuid") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_aprobado_por" FOREIGN KEY ("aprobado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_rechazado_por" FOREIGN KEY ("rechazado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendios" ADD CONSTRAINT "fk_incendios_estado" FOREIGN KEY ("estado_incendio_uuid") REFERENCES "estado_incendio"("estado_incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" ADD CONSTRAINT "fk_resp_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" ADD CONSTRAINT "fk_resp_institucion_uuid" FOREIGN KEY ("institucion_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "municipios" ADD CONSTRAINT "fk_municipios_departamento_uuid" FOREIGN KEY ("departamento_uuid") REFERENCES "departamentos"("departamento_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes" ADD CONSTRAINT "fk_reportes_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes" ADD CONSTRAINT "fk_reportes_reportado_por_uuid" FOREIGN KEY ("reportado_por_uuid") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes" ADD CONSTRAINT "fk_reportes_institucion_uuid" FOREIGN KEY ("institucion_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes" ADD CONSTRAINT "fk_reportes_medio_uuid" FOREIGN KEY ("medio_uuid") REFERENCES "medios"("medio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes" ADD CONSTRAINT "fk_reportes_departamento_uuid" FOREIGN KEY ("departamento_uuid") REFERENCES "departamentos"("departamento_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reportes" ADD CONSTRAINT "fk_reportes_municipio_uuid" FOREIGN KEY ("municipio_uuid") REFERENCES "municipios"("municipio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" ADD CONSTRAINT "fk_historial_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" ADD CONSTRAINT "fk_historial_estado_uuid" FOREIGN KEY ("estado_incendio_uuid") REFERENCES "estado_incendio"("estado_incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" ADD CONSTRAINT "fk_historial_cambiado_por" FOREIGN KEY ("cambiado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fotos_reporte" ADD CONSTRAINT "fk_fotos_reporte_reporte_uuid" FOREIGN KEY ("reporte_uuid") REFERENCES "reportes"("reporte_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zonas_afectadas" ADD CONSTRAINT "fk_zonas_afectadas_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_operaciones" ADD CONSTRAINT "fk_cierre_operaciones_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_operaciones" ADD CONSTRAINT "fk_cierre_operaciones_tipo_incendio" FOREIGN KEY ("tipo_incendio_principal_id") REFERENCES "tipos_incendio"("tipo_incendio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "puntos_calor" ADD CONSTRAINT "fk_puntos_calor_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" ADD CONSTRAINT "fk_eventos_operativos_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" ADD CONSTRAINT "fk_eventos_operativos_creado_por" FOREIGN KEY ("creado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_creado_por" FOREIGN KEY ("creado_por") REFERENCES "usuarios"("usuario_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_historial_uuid" FOREIGN KEY ("historial_uuid") REFERENCES "incendio_estado_historial"("historial_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_reporte_uuid" FOREIGN KEY ("reporte_uuid") REFERENCES "reportes"("reporte_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_foto_reporte_uuid" FOREIGN KEY ("foto_reporte_uuid") REFERENCES "fotos_reporte"("foto_reporte_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_responsable_uuid" FOREIGN KEY ("responsable_incendio_uuid") REFERENCES "incendio_registro_responsable"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_cierre_uuid" FOREIGN KEY ("cierre_incendio_uuid") REFERENCES "cierre_operaciones"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_zona_uuid" FOREIGN KEY ("zona_afectada_uuid") REFERENCES "zonas_afectadas"("zona_afectada_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_punto_calor_uuid" FOREIGN KEY ("punto_calor_uuid") REFERENCES "puntos_calor"("punto_calor_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" ADD CONSTRAINT "fk_actualizaciones_evento_operativo_uuid" FOREIGN KEY ("evento_operativo_uuid") REFERENCES "cierre_eventos_operativos"("evento_operativo_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_topografia" ADD CONSTRAINT "fk_cierre_topografia_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_tecnicas_extincion" ADD CONSTRAINT "fk_tecnicas_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_superficie" ADD CONSTRAINT "fk_cierre_superficie_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_superficie_vegetacion" ADD CONSTRAINT "fk_superficie_veg_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_secuencia_control" ADD CONSTRAINT "fk_cierre_secuencia_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_propiedad" ADD CONSTRAINT "fk_cierre_propiedad_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_propiedad" ADD CONSTRAINT "fk_cierre_propiedad_tipo" FOREIGN KEY ("tipo_propiedad_id") REFERENCES "tipo_propiedad"("tipo_propiedad_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_meteorologia" ADD CONSTRAINT "fk_cierre_meteo_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_terrestres" ADD CONSTRAINT "fk_medios_terr_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_terrestres" ADD CONSTRAINT "fk_medios_terr_catalogo" FOREIGN KEY ("medio_terrestre_id") REFERENCES "medios_terrestres_catalogo"("medio_terrestre_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_instituciones" ADD CONSTRAINT "fk_medios_inst_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_instituciones" ADD CONSTRAINT "fk_medios_inst_institucion_uuid" FOREIGN KEY ("institucion_uuid") REFERENCES "instituciones"("institucion_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_acuaticos" ADD CONSTRAINT "fk_medios_acua_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_acuaticos" ADD CONSTRAINT "fk_medios_acua_catalogo" FOREIGN KEY ("medio_acuatico_id") REFERENCES "medios_acuaticos_catalogo"("medio_acuatico_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_aereos" ADD CONSTRAINT "fk_medios_aereos_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_aereos" ADD CONSTRAINT "fk_medios_aereos_catalogo" FOREIGN KEY ("medio_aereo_id") REFERENCES "medios_aereos_catalogo"("medio_aereo_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_iniciado_junto_a" ADD CONSTRAINT "fk_cierre_iniciado_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_iniciado_junto_a" ADD CONSTRAINT "fk_cierre_iniciado_catalogo" FOREIGN KEY ("iniciado_id") REFERENCES "iniciado_junto_a_catalogo"("iniciado_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_composicion_tipo" ADD CONSTRAINT "fk_comp_tipo_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_composicion_tipo" ADD CONSTRAINT "fk_comp_tipo_tipo" FOREIGN KEY ("tipo_incendio_id") REFERENCES "tipos_incendio"("tipo_incendio_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_causa" ADD CONSTRAINT "fk_cierre_causa_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_causa" ADD CONSTRAINT "fk_cierre_causa_catalogo" FOREIGN KEY ("causa_id") REFERENCES "causas_catalogo"("causa_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_abastos" ADD CONSTRAINT "fk_abastos_incendio_uuid" FOREIGN KEY ("incendio_uuid") REFERENCES "incendios"("incendio_uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cierre_abastos" ADD CONSTRAINT "fk_abastos_catalogo" FOREIGN KEY ("abasto_id") REFERENCES "abastos_catalogo"("abasto_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cierre_abastos" DROP CONSTRAINT "fk_abastos_catalogo"`);
        await queryRunner.query(`ALTER TABLE "cierre_abastos" DROP CONSTRAINT "fk_abastos_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_causa" DROP CONSTRAINT "fk_cierre_causa_catalogo"`);
        await queryRunner.query(`ALTER TABLE "cierre_causa" DROP CONSTRAINT "fk_cierre_causa_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_composicion_tipo" DROP CONSTRAINT "fk_comp_tipo_tipo"`);
        await queryRunner.query(`ALTER TABLE "cierre_composicion_tipo" DROP CONSTRAINT "fk_comp_tipo_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_iniciado_junto_a" DROP CONSTRAINT "fk_cierre_iniciado_catalogo"`);
        await queryRunner.query(`ALTER TABLE "cierre_iniciado_junto_a" DROP CONSTRAINT "fk_cierre_iniciado_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_aereos" DROP CONSTRAINT "fk_medios_aereos_catalogo"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_aereos" DROP CONSTRAINT "fk_medios_aereos_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_acuaticos" DROP CONSTRAINT "fk_medios_acua_catalogo"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_acuaticos" DROP CONSTRAINT "fk_medios_acua_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_instituciones" DROP CONSTRAINT "fk_medios_inst_institucion_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_instituciones" DROP CONSTRAINT "fk_medios_inst_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_terrestres" DROP CONSTRAINT "fk_medios_terr_catalogo"`);
        await queryRunner.query(`ALTER TABLE "cierre_medios_terrestres" DROP CONSTRAINT "fk_medios_terr_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_meteorologia" DROP CONSTRAINT "fk_cierre_meteo_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_propiedad" DROP CONSTRAINT "fk_cierre_propiedad_tipo"`);
        await queryRunner.query(`ALTER TABLE "cierre_propiedad" DROP CONSTRAINT "fk_cierre_propiedad_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_secuencia_control" DROP CONSTRAINT "fk_cierre_secuencia_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_superficie_vegetacion" DROP CONSTRAINT "fk_superficie_veg_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_superficie" DROP CONSTRAINT "fk_cierre_superficie_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_tecnicas_extincion" DROP CONSTRAINT "fk_tecnicas_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_topografia" DROP CONSTRAINT "fk_cierre_topografia_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_evento_operativo_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_punto_calor_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_zona_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_cierre_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_responsable_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_foto_reporte_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_reporte_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_historial_uuid"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_creado_por"`);
        await queryRunner.query(`ALTER TABLE "actualizaciones" DROP CONSTRAINT "fk_actualizaciones_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" DROP CONSTRAINT "fk_eventos_operativos_creado_por"`);
        await queryRunner.query(`ALTER TABLE "cierre_eventos_operativos" DROP CONSTRAINT "fk_eventos_operativos_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "puntos_calor" DROP CONSTRAINT "fk_puntos_calor_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "cierre_operaciones" DROP CONSTRAINT "fk_cierre_operaciones_tipo_incendio"`);
        await queryRunner.query(`ALTER TABLE "cierre_operaciones" DROP CONSTRAINT "fk_cierre_operaciones_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "zonas_afectadas" DROP CONSTRAINT "fk_zonas_afectadas_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "fotos_reporte" DROP CONSTRAINT "fk_fotos_reporte_reporte_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" DROP CONSTRAINT "fk_historial_cambiado_por"`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" DROP CONSTRAINT "fk_historial_estado_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_estado_historial" DROP CONSTRAINT "fk_historial_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "reportes" DROP CONSTRAINT "fk_reportes_municipio_uuid"`);
        await queryRunner.query(`ALTER TABLE "reportes" DROP CONSTRAINT "fk_reportes_departamento_uuid"`);
        await queryRunner.query(`ALTER TABLE "reportes" DROP CONSTRAINT "fk_reportes_medio_uuid"`);
        await queryRunner.query(`ALTER TABLE "reportes" DROP CONSTRAINT "fk_reportes_institucion_uuid"`);
        await queryRunner.query(`ALTER TABLE "reportes" DROP CONSTRAINT "fk_reportes_reportado_por_uuid"`);
        await queryRunner.query(`ALTER TABLE "reportes" DROP CONSTRAINT "fk_reportes_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "municipios" DROP CONSTRAINT "fk_municipios_departamento_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" DROP CONSTRAINT "fk_resp_institucion_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendio_registro_responsable" DROP CONSTRAINT "fk_resp_incendio_uuid"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_estado"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_rechazado_por"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_aprobado_por"`);
        await queryRunner.query(`ALTER TABLE "incendios" DROP CONSTRAINT "fk_incendios_creado_por_uuid"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "fk_usuarios_institucion_uuid"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "fk_usuarios_rol_uuid"`);
        await queryRunner.query(`DROP TABLE "auditoria_eventos"`);
        await queryRunner.query(`DROP TABLE "cierre_abastos"`);
        await queryRunner.query(`DROP TABLE "abastos_catalogo"`);
        await queryRunner.query(`DROP TABLE "cierre_causa"`);
        await queryRunner.query(`DROP TABLE "causas_catalogo"`);
        await queryRunner.query(`DROP TABLE "cierre_composicion_tipo"`);
        await queryRunner.query(`DROP TABLE "cierre_iniciado_junto_a"`);
        await queryRunner.query(`DROP TABLE "iniciado_junto_a_catalogo"`);
        await queryRunner.query(`DROP TABLE "cierre_medios_aereos"`);
        await queryRunner.query(`DROP TABLE "medios_aereos_catalogo"`);
        await queryRunner.query(`DROP TABLE "cierre_medios_acuaticos"`);
        await queryRunner.query(`DROP TABLE "medios_acuaticos_catalogo"`);
        await queryRunner.query(`DROP TABLE "cierre_medios_instituciones"`);
        await queryRunner.query(`DROP TABLE "cierre_medios_terrestres"`);
        await queryRunner.query(`DROP TABLE "medios_terrestres_catalogo"`);
        await queryRunner.query(`DROP TABLE "cierre_meteorologia"`);
        await queryRunner.query(`DROP TABLE "cierre_propiedad"`);
        await queryRunner.query(`DROP TABLE "tipo_propiedad"`);
        await queryRunner.query(`DROP TABLE "cierre_secuencia_control"`);
        await queryRunner.query(`DROP INDEX "public"."idx_superficie_veg_incendio_categoria"`);
        await queryRunner.query(`DROP TABLE "cierre_superficie_vegetacion"`);
        await queryRunner.query(`DROP TABLE "cierre_superficie"`);
        await queryRunner.query(`DROP TABLE "cierre_tecnicas_extincion"`);
        await queryRunner.query(`DROP TABLE "cierre_topografia"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actualizaciones_incendio_fecha"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actualizaciones_creado_en"`);
        await queryRunner.query(`DROP TABLE "actualizaciones"`);
        await queryRunner.query(`DROP INDEX "public"."idx_eventos_operativos_incendio_fecha"`);
        await queryRunner.query(`DROP TABLE "cierre_eventos_operativos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_puntos_calor_fecha"`);
        await queryRunner.query(`DROP TABLE "puntos_calor"`);
        await queryRunner.query(`DROP TABLE "cierre_operaciones"`);
        await queryRunner.query(`DROP TABLE "tipos_incendio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zonas_afectadas_incendio_fecha"`);
        await queryRunner.query(`DROP TABLE "zonas_afectadas"`);
        await queryRunner.query(`DROP INDEX "public"."idx_fotos_reporte_reporte"`);
        await queryRunner.query(`DROP TABLE "fotos_reporte"`);
        await queryRunner.query(`DROP INDEX "public"."idx_historial_incendio_fecha"`);
        await queryRunner.query(`DROP TABLE "incendio_estado_historial"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reportes_incendio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reportes_reportado_en"`);
        await queryRunner.query(`DROP TABLE "reportes"`);
        await queryRunner.query(`DROP INDEX "public"."uq_municipios_depto_nombre"`);
        await queryRunner.query(`DROP INDEX "public"."idx_municipios_depto_nombre"`);
        await queryRunner.query(`DROP TABLE "municipios"`);
        await queryRunner.query(`DROP TABLE "departamentos"`);
        await queryRunner.query(`DROP TABLE "medios"`);
        await queryRunner.query(`DROP TABLE "incendio_registro_responsable"`);
        await queryRunner.query(`DROP INDEX "public"."idx_incendios_estado_aprobado"`);
        await queryRunner.query(`DROP TABLE "incendios"`);
        await queryRunner.query(`DROP TABLE "estado_incendio"`);
        await queryRunner.query(`DROP INDEX "public"."uq_usuarios_email_notnull"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "instituciones"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
